### ISSUE TITLE
how to init without initial connection and retry connection after failure every 1 or 3s or so.

### ISSUE THREAD

**Issue by ultperf** [rueian/rueidis#126]
I realised this needs to be "connected". Is it possible not to have the connection because i'm running the client first then only in main() is the server part. both client and server is on the same 1 program. the error is shown and i cant use the Credises.Load(i) because it failed. Is it possible for it to re-connect on failure and dont do "err :=" returned?

```
ERR = dial tcp 127.0.0.1:6379: connect: connection refused
```

```
func init() {
  for i:=0;i<10;i++ {
    credis, err := rueidis.NewClient(rueidis.ClientOption{
		    InitAddress: []string{"127.0.0.1:6379"},
    })
    if err == nil {
      Credises.Store(i, credis)
      log.Printf("good = %v", i)
    } else {
    log.Printf("ERR = %s", err)
    }
  }
}
```

**Comment by rueian** [comment]
Hi @ultperf,

You will at least need to listen those ports first with `net.Listen` to avoid `rueidis.NewClient` failed.

You can also let `rueidis.NewClient` concurrent with your server initialization.

**Comment by ultperf** [comment]
what happens when the tcp connection failed? how to retry "init" every 3 seconds"?

**Comment by rueian** [comment]
Hi @ultperf,

Try this:
```go
func main() {
	go func() {
		for {
			c, err := rueidis.NewClient(rueidis.ClientOption{
				InitAddress: []string{"..."},
			})
			if err == nil {
				// store the c
				break
			}
		}
	}()
	// initialize your server
	...
}
```
Once the `rueidis.Client` is constructed, it will try reconnect when the underlying connection failed.

**Comment by ultperf** [comment]
i can store c but it seems if the first init is not working, then it wont even retry it. it needs to be able to connect first time first. right? possible to have something where first init can fail but subsequent retry can work?
```
			c, err := rueidis.NewClient(rueidis.ClientOption{
				InitAddress: []string{"..."},
			})
			if err == nil {
				// store the c
				break
			}
```

**Comment by rueian** [comment]
> i can store c but it seems if the first init is not working, then it wont even retry it. it needs to be able to connect first time first. right? 

Yes, it need to be able to connect to the server in first time because how does `rueidis.Client` be constructed is determined by the first connection.

However, you can still retry the first connection with a loop like this:

```go
		for {
			c, err := rueidis.NewClient(rueidis.ClientOption{
				InitAddress: []string{"..."},
			})
			if err == nil {
				// store the c, and stop retrying
				break
			}
		}
```

**Comment by ultperf** [comment]
this is not going to work because of my prefork limitations.
possible not to be able to connect to the server the first time? (BUT only subsequent tries? //<- i dunno how this is going to work)

what i am saying is, i really would like to have it without connecting the first time. possible to code this into the client?

pls do this coz almost all other clients dont have this requirement and migrating from them to rueidis can be much easier.

thx in advance.

**Comment by rueian** [comment]
> this is not going to work because of my prefork limitations.

Could you elaborate more about your limitations? I thought the proposed retry mechanism shouldn’t have anything to do with your limitations.

**Comment by hiqsociety** [comment]
i'm using prefork mode so i cannot do init address first because the each server is tied to cpu.
the servers will only run after client is ran.
i have done a mock tcp server that listens per port for each core BUT not sure why it's still error in connection. so not sure what data needs to be returned to ruiedis for it to approve of the connection.

all other redis golang client dont need init connection. so i'm just migrating old client connector to this and seems like first connection must happen (so i did a mock tcp) BUT not sure why it's rejected. the connection needs detect what values in return to return non error?

else pls make it so that i can specify the address without connecting and connection only happens when it's first called.

**Comment by rueian** [comment]
> i'm using prefork mode so i cannot do init address first because the each server is tied to cpu.
> the servers will only run after client is ran.
> i have done a mock tcp server that listens per port for each core BUT not sure why it's still error in connection. so not sure what data needs to be returned to ruiedis for it to approve of the connection.

I also mocking tcp server in testing, for example here and here: https://github.com/rueian/rueidis/blob/master/pipe_test.go#L134-L145, https://github.com/rueian/rueidis/blob/master/pipe_test.go#L211-L219

> BUT not sure why it's rejected

Could you share the error message?

> all other redis golang client dont need init connection. else pls make it so that i can specify the address without connecting and connection only happens when it's first called (or used)

I believe delaying the first connection is actually not a good practice, since it will delay configuration errors such as wrong address, wrong username/password, and etc.

However, it is not too hard to build something similar to such practice, for example:
```go
type cpool struct {
	mu sync.Mutex
	cm map[string]rueidis.Client
}

func (p *cpool) Get(addr string) (c rueidis.Client, err error) {
	p.mu.Lock()
	defer p.mu.Unlock()
	if c = p.cm[addr]; c == nil {
		if c, err = rueidis.NewClient(rueidis.ClientOption{InitAddress: []string{addr}}); err == nil {
			p.cm[addr] = c
		}
	}
	return
}
```

**Comment by ultperf** [comment]
ok i try tml and get back to u, thx

**Comment by ultperf** [comment]
// getting assignment to entry in nil map... how to resolve?
```
type cpool struct {
	mu sync.Mutex
	cm map[string]rueidis.Client
}

func (p *cpool) Get(addr string) (c rueidis.Client, err error) {
	p.mu.Lock()
	defer p.mu.Unlock()
	if c = p.cm[addr]; c == nil {
		if c, err = rueidis.NewClient(rueidis.ClientOption{InitAddress: []string{addr}}); err == nil {
			p.cm[addr] = c // getting assignment to entry in nil map... how to resolve?
		}
	}
	return
}
```
