### ISSUE TITLE
Question: KeyMajority for distributed locking

### ISSUE THREAD

**Issue by kamikazechaser** [rueian/rueidis#161]
Is the KeyMajority related to number of connected instances? If I have a cluster of 3 redis servers, it needs to get a lock on at least 2 if KeyMajority is set to 2, right?

If that is the case, shouldn't the KeyMajority be set automatically depending in the  no. of connected instances? i.e. if InitAddress contains one address, the KeyMajority should automatically default to 1.

**Comment by rueian** [comment]
Hi @kamikazechaser,

> Is the KeyMajority related to number of connected instances? If I have a cluster of 3 redis servers, it needs to get a lock on at least 2 if KeyMajority is set to 2, right?

Yes, you should set it to 2, at least.

> If that is the case, shouldn't the KeyMajority be set automatically depending in the no. of connected instances? i.e. if InitAddress contains one address, the KeyMajority should automatically default to 1.

It is important to note that all your `rueidislock.NewLocker` should share the same `KeyMajority`, otherwise they will falsely believe they acquire some locks. Furthermore, redis instances, as well as your application, will come and go at any time.

So... Simply choosing the `KeyMajority` based on the number of connected redis instances is probably not a good idea. It will easily produce different `KeyMajority` setups.

**Comment by kamikazechaser** [comment]
Ah I see. Makes sense. So in short KeyMajority should be atleast `n - 1 or 1 if n = 1`.

**Comment by kamikazechaser** [comment]
Ah ok. Thanks! I'll mark this as closed.
