### ISSUE TITLE
Question about transactions in a cluster

### ISSUE THREAD

**Issue by lsgndln** [rueian/rueidis#196]
Hello ! I have a question regarding transactions in a cluster.

 We are migrating from go-redis to rueidis, and we are using transactions. Before, we were using the `TxPipelined` method from go-redis, which seems to wrap the commands between a MULTI and an EXEC.

I tried to do something similar, using a dedicated connection that sends the wrapped commands in a `DoMulti` but it is not working well, I get this error : `cross slot command in Dedicated is prohibited`.

Should I not use the dedicated connection in this case ? I tried to check the go-redis implementation but seems like they are doing a similar thing.

Thanks again 🙏

**Comment by rueian** [comment]
Hi @lsgndln,

The reason behind the error `cross slot command in Dedicated is prohibited.` is a dedicated client needs to find which redis node in the cluster it should connect to from the first command. 

If the first command is a `DoMulti` and mixed with multiple key slots, it will be difficult to choose the key slot. However,  I believe the condition of this error can be relaxed once the key slot is fixed in the next version.

On the other hand, if you use `MULTI` and `EXEC` without `WATCH` then a dedicated connection is not needed.

**Comment by rueian** [comment]
Hi @lsgndln,

The fix is here: https://github.com/rueian/rueidis/commit/8d8be3ff98f766e239b2a492e55b6afe7b62f40c

and will be released this weekend.

**Comment by rueian** [comment]
Hi @lsgndln, the fix has been added in the v0.0.99.
