### ISSUE TITLE
Add ability to disable local caching

### ISSUE THREAD

**Issue by GiedriusS** [rueian/rueidis#79]
Currently, "cache size each conn" is set to the default value if `0` is provided: https://github.com/rueian/rueidis/blob/master/rueidis.go#L201-L203, https://github.com/rueian/rueidis/blob/8b21fc0a8614397bbe4beada7292f2b9431a9d18/pipe.go#L63. Perhaps we could skip the `LRU` entirely if zero has been passed? However, that would be a breaking change. Perhaps a separate flag could exist such as `DisableLocalCache`?

Ran into this while doing https://github.com/thanos-io/thanos/pull/5593. I think some users might not want to cache items locally if their systems don't have much RAM, for example.

**Comment by rueian** [comment]
Sure, a separate flag to disable the cache is much easier to implement.

**Comment by rueian** [comment]
Hi @GiedriusS,

v0.0.71 now has a `ClientOption.DisableCache` that will fall back `Client.DoCache/Client.DoMultiCache` to `Client.Do/Client.DoMulti` and effectively disable client-side caching.

In terms of the second thing, `There's no way to disable the default TTL in case PTTL fails` you mentioned in the https://github.com/thanos-io/thanos/pull/5593. Since the PTTL is sent inside the same redis `MULTI EXEC` block of the target command, it is guaranteed that PTTL succeeds if you get the target response.

**Comment by GiedriusS** [comment]
I see. I am reading the code a bit now. So, it doesn't matter what `time.Duration` we pass to `MGetCache`? :thinking:

**Comment by rueian** [comment]
Hi @GiedriusS,

The time.Duration you passed will take effect in two cases:
1. The time.Duration is smaller than PTTL response.
2. The key on redis has no TTL

**Comment by GiedriusS** [comment]
I see, it makes sense! Thank you for the response. I'll continue on with https://github.com/thanos-io/thanos/pull/5593.
